### ISSUE TITLE
Worker events are called for no reason

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module#92] opened 2021-11-29 19:06 UTC
### Description of the problem

Worker events are called for no reason if event subscribers were registered in the load event

### Reproduction steps

```js
import * as alt from "alt-client"

// can be empty file
const worker = new alt.Worker("./worker.js") 
worker.start()

worker.on("load", () => {
  alt.log("worker ~gl~load")

  worker.on("im called for no reason", (data) => {
    alt.log("im called for no reason data:", JSON.stringify(data))
  })
})

```

### Expected behaviour

These events should not be triggered for no reason

### Operating system

Windows 10

### Version

dev/7.0-dev21

### Scope

client

**Comment by LeonMrBonnie** [comment] 2021-11-29 20:11
Well, I know what the problem is but I don't know how to fix it, so this is a won't fix for now.
Just don't register event handlers inside worker event handlers for now xd

**Comment by LeonMrBonnie** [comment] 2021-11-29 20:44
Nevermind, I am very smart so I fixed it

**Closed by LeonMrBonnie** 2021-11-29 20:44 UTC
Labels: type: bug

**Comment by xxshady** [comment] 2021-11-29 20:45
xd

**Comment by xxshady** [comment] 2021-11-29 20:47
I always knew you could do it!
